### ISSUE TITLE
Will this module supports AOSP roms?

### ISSUE THREAD

**Issue by M1sterXXL** [anonymix007/ExtA2DP#17]
there are a little number os CLO roms for my devices.
or i can do sth to support certain rom?

**Comment by anonymix007** [comment]
You can ask ROM dev to switch to QTI BT stack. 

I'm planning to bundle both `libbluetooth_qti.so` and `libbluetooth_qti_jni.so` in A14 version (not just `libbluetooth_qti.so` rebranded to `libbluetooth_exta2dp.so` as it's done currently), which should improve compatibility. It may not be enough for AOSP BT stack though (especially if it's in apex), but at that point it should be easy to make a non-CLO module version just by replacing these `libbluetooth*.so`. I personally don't want to maintain it (because once again, XPAN support which I'm going to try to implement in the future is only possible with QTI BT stack), but you may do so (see [android_packages_modules_Bluetooth](https://github.com/anonymix007/android_packages_modules_Bluetooth)).

**Comment by Yuvi0912** [comment]
Hey why closed ?

**Comment by anonymix007** [comment]
I decided to track all the progress in #13. There isn't any as of now, but hopefully one of A15 releases will be available for both CLO and AOSP ROMs

**Comment by Yuvi0912** [comment]
Oh okay, I don't guess there is any other alternative as of now other than switching to stock rom then.
Thanks for the support let me know if you need testers
