### ISSUE TITLE
[Request] Android 12 support

### ISSUE THREAD

**Issue by STUkh** [anonymix007/ExtA2DP#25]
**First of all that you for such a great project!**
I was inspired by your contribution and tried to run or at least partly migrate your project to bring LHDC codecs into Android 12.
Especially it would be handle for HiBy players that utilise AOSP 12 but lack of LHDC codecs and can be relatively easy rooted.
I'm rookie in android development, but fast learning and was able to pre-build `api-release.aar` and `service-release.aar` but can't handle out where you get `interface-release.aar`? Trying just build from you sources as first step.

And another bunch of questions that will save some time:
- Will `.so` libs will work on Android 12?
- How do you think is downgrade from 2.3.0 API32 -> API31 would be challenge?

Actually appreciate for any help that can bring LHDC to android 12.

**Comment by anonymix007** [comment]
> where you get `interface-release.aar`

AFAIR I built it once from
https://github.com/libxposed/service/tree/master/interface and used it since then.

> Will `.so` libs will work on Android 12?

No. It's usually impossible to keep compatibility even between QPRs. Current libraries are for A14 and do not work anywhere else. Same for the last A13 release. And once I start working on A15 version, even A14 version will no longer be maintained.

> How do you think is downgrade from 2.3.0 API32 -> API31 would be challenge?

It shouldn't be too hard, but will definitely take a lot of time.
